"""
Document ingestion for the codegen pipeline.

Takes a PDF or Word document that may contain an HLD, LLD, or ER diagram
(as an embedded image, or as a whole page that IS a diagram), and produces:
  - the document's raw text
  - a plain-English description of every diagram found, generated by
    sending each diagram image to Gemini's vision capability

This is the stage that lets the pipeline handle "a document with a diagram
in it" rather than only plain text.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass, field
from pathlib import Path

import fitz  # PyMuPDF
from docx import Document as DocxDocument
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage

# Pages/images smaller than this are almost certainly logos or icons, not
# an actual HLD/LLD/ER diagram - skip them so we don't waste a vision call
# (and tokens) describing a company logo.
MIN_DIAGRAM_DIMENSION_PX = 200

DIAGRAM_DESCRIPTION_PROMPT = """\
You are looking at an image extracted from a technical design document.

If this image is a High-Level Design (HLD), Low-Level Design (LLD), or
Entity-Relationship (ER) diagram, describe it in structured plain text:
- List every entity/component/service shown.
- For an ER diagram: list each entity's fields and its relationships to
  other entities (one-to-one, one-to-many, many-to-many) and which fields
  are keys.
- For an HLD/LLD: list each component/service, what it does, and how data
  flows between them.

If this image is NOT a design diagram (e.g. it's a logo, a decorative
image, a screenshot of unrelated content), respond with exactly:
NOT_A_DIAGRAM

Be concise but complete - this description will be used as the sole source
of truth about this diagram for a code generation task, so do not omit any
entity, field, or relationship that is visible.
"""


@dataclass
class IngestedDocument:
    text: str
    diagram_descriptions: list[str] = field(default_factory=list)

    def combined_context(self) -> str:
        """Everything the codegen prompt needs, in one block."""
        parts = [self.text.strip()]
        for i, desc in enumerate(self.diagram_descriptions, start=1):
            parts.append(f"\n--- Diagram {i} description ---\n{desc.strip()}")
        return "\n".join(p for p in parts if p)


def _describe_image(image_bytes: bytes, model: ChatGoogleGenerativeAI) -> str | None:
    """Send one image to Gemini vision; return its description, or None if
    the model decided this wasn't a design diagram at all."""
    b64 = base64.b64encode(image_bytes).decode("utf-8")
    message = HumanMessage(
        content=[
            {"type": "text", "text": DIAGRAM_DESCRIPTION_PROMPT},
            {
                "type": "image_url",
                "image_url": {"url": f"data:image/png;base64,{b64}"},
            },
        ]
    )
    response = model.invoke([message])
    text = response.content.strip()
    if text == "NOT_A_DIAGRAM":
        return None
    return text


def _ingest_pdf(path: Path, model: ChatGoogleGenerativeAI) -> IngestedDocument:
    doc = fitz.open(path)
    full_text = []
    diagram_descriptions = []

    for page in doc:
        full_text.append(page.get_text())

        # Embedded images (e.g. a diagram pasted into a Word-exported PDF)
        for img_info in page.get_images(full=True):
            xref = img_info[0]
            base_image = doc.extract_image(xref)
            if base_image["width"] < MIN_DIAGRAM_DIMENSION_PX or \
               base_image["height"] < MIN_DIAGRAM_DIMENSION_PX:
                continue
            description = _describe_image(base_image["image"], model)
            if description:
                diagram_descriptions.append(description)

        # Whole-page render: catches diagrams that are actually vector
        # drawings on the page rather than an embedded raster image (common
        # for ER diagrams exported from design tools).
        if not page.get_images(full=True) and len(page.get_text().strip()) < 50:
            pix = page.get_pixmap(dpi=150)
            description = _describe_image(pix.tobytes("png"), model)
            if description:
                diagram_descriptions.append(description)

    doc.close()
    return IngestedDocument(
        text="\n".join(full_text),
        diagram_descriptions=diagram_descriptions,
    )


def _ingest_docx(path: Path, model: ChatGoogleGenerativeAI) -> IngestedDocument:
    doc = DocxDocument(path)
    full_text = "\n".join(p.text for p in doc.paragraphs)

    diagram_descriptions = []
    for rel in doc.part.rels.values():
        if "image" not in rel.target_ref:
            continue
        image_bytes = rel.target_part.blob
        description = _describe_image(image_bytes, model)
        if description:
            diagram_descriptions.append(description)

    return IngestedDocument(text=full_text, diagram_descriptions=diagram_descriptions)


def ingest_document(path: str | Path, model: ChatGoogleGenerativeAI) -> IngestedDocument:
    """Entry point: give it any supported file path, get back extracted
    text + diagram descriptions, regardless of file type."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"No file at: {path}")

    suffix = path.suffix.lower()
    if suffix == ".pdf":
        return _ingest_pdf(path, model)
    elif suffix == ".docx":
        return _ingest_docx(path, model)
    elif suffix in (".txt", ".md"):
        return IngestedDocument(text=path.read_text(), diagram_descriptions=[])
    else:
        raise ValueError(
            f"Unsupported file type '{suffix}'. Supported: .pdf, .docx, .txt, .md"
        )
